name: build and release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Install packages & setup
        run: |
          sudo apt update -y
          sudo apt-get update --fix-missing && sudo apt-get install bc bison build-essential zstd clang flex gnupg gperf ccache liblz4-tool libsdl1.2-dev libstdc++6 libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev libncurses5-dev python3 bzip2 git gcc g++ libssl-dev openssl -y && sudo apt-get install gcc-aarch64-linux-gnu -y && sudo apt-get install gcc-arm-linux-gnueabihf -y && sudo apt-get install lld gcc-arm-linux-gnueabi llvm python-is-python3 device-tree-compiler cpio -y
          bash init_clang_13.sh
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Building LPoS + KernelSU
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -k

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS-${{ env.LPOS_KERNEL_VERSION }}-[Note 10]"
          path: |
            out/KSU*.zip
