name: Build and Release

on:
  workflow_dispatch:        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Install packages & setup
        run: |
          sudo apt update -y
          sudo apt install libncurses5-dev -y
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Building LPoS + KernelSU
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -k

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS-${{ env.LPOS_KERNEL_VERSION }}-[Note 10]"
          path: |
            out/KSU*.zip
